version: 2
models:
  - name: customers
    description: "{{ doc('customers') }}"
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
  - name: orders
    description: Finalizes clean order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Every order needs a customer
        tests:
          - not_null
      - name: amount
        description: Amount paid for order
        tests:
          - not_null
sources:
  - name: jaffle_shop
    database: raw
    tables: 
      - name: customers
      - name: orders
        columns:
          - name: id
            tests:
              - not_null
              - unique
              
        loaded_at_field: _etl_loaded_at

        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

  - name: stripe
    database: raw
    tables:
      - name: payment